//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR.SP.IdeaTracker.WebParts.IdeaStageWP {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class IdeaStageWP {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbParti;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(IdeaStageWP target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbParti() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbParti = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbParti";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(280D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::MR.SP.IdeaTracker.WebParts.IdeaStageWP.IdeaStageWP @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../_layouts/15/images/MR.SP.IdeaTr" +
                        "acker/CSS/IdeaCSS.css\" />\r\n\r\n<style type=\"text/css\">\r\n    .auto-style3 {\r\n      " +
                        "  width: 50px;\r\n        height: 40px;\r\n    }\r\n</style>\r\n\r\n<div class=\"divBox\">\r\n" +
                        "    <table border=\"0\" class=\"stageTable\">\r\n        <tr>\r\n            <td>\r\n     " +
                        "           <img alt=\"\" src=\"../_layouts/15/images/MR.SP.IdeaTracker/Images/Class" +
                        "ification.png\" /></td>\r\n            <td>\r\n                <img alt=\"\" src=\"../_l" +
                        "ayouts/15/images/MR.SP.IdeaTracker/Images/Decision.png\" /></td>\r\n        </tr>\r\n" +
                        "        <tr>\r\n            <td colspan=\"2\">\r\n                <h2>Idea Stage</h2>\r" +
                        "\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td colspan=\"2\">\r\n " +
                        "               <table border=\"0\" class=\"stageTable\">\r\n                    <tr>\r\n" +
                        "                        <td>\r\n                            <img alt=\"\" class=\"aut" +
                        "o-style3\" src=\"../_layouts/15/images/MR.SP.IdeaTracker/Images/Stages/BlackS.png\"" +
                        " /></td>\r\n                        <td>\r\n                            <img alt=\"\" " +
                        "class=\"auto-style3\" src=\"../_layouts/15/images/MR.SP.IdeaTracker/Images/Stages/G" +
                        "rayC.png\" /></td>\r\n                        <td>\r\n                            <im" +
                        "g alt=\"\" class=\"auto-style3\" src=\"../_layouts/15/images/MR.SP.IdeaTracker/Images" +
                        "/Stages/GrayO.png\" /></td>\r\n                        <td>\r\n                      " +
                        "      <img alt=\"\" class=\"auto-style3\" src=\"../_layouts/15/images/MR.SP.IdeaTrack" +
                        "er/Images/Stages/GrayR.png\" /></td>\r\n                        <td>\r\n             " +
                        "               <img alt=\"\" class=\"auto-style3\" src=\"../_layouts/15/images/MR.SP." +
                        "IdeaTracker/Images/Stages/GrayE.png\" /></td>\r\n                    </tr>\r\n       " +
                        "         </table>\r\n            </td>\r\n        </tr>\r\n        <tr><td colspan=\"2\"" +
                        " class=\"splitTD\"></td></tr>\r\n        <tr>\r\n            <td colspan=\"2\">\r\n       " +
                        "         <span class=\"blueSpan\">Add Minutes/Notes</span>\r\n            </td>\r\n   " +
                        "     </tr>\r\n        <tr><td colspan=\"2\" class=\"splitTD\"></td></tr>\r\n        <tr>" +
                        "\r\n            <td colspan=\"2\">\r\n                <span class=\"orangeSpan\">Add Act" +
                        "ions</span>\r\n            </td>\r\n        </tr>\r\n        <tr><td colspan=\"2\" class" +
                        "=\"splitTD\"></td></tr>\r\n        <tr>\r\n            <td colspan=\"2\">\r\n             " +
                        "   <span class=\"purpleSpan\">Add Attachments</span>\r\n            </td>\r\n        <" +
                        "/tr>\r\n        <tr><td colspan=\"2\" class=\"splitTD\"></td></tr>\r\n        <tr>\r\n    " +
                        "        <td colspan=\"2\">\r\n                <span class=\"oliverSpan\">Innovation In" +
                        "dex</span>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td cols" +
                        "pan=\"2\">\r\n                <h2>Participants</h2>\r\n            </td>\r\n        </tr" +
                        ">\r\n        <tr>\r\n            <td colspan=\"2\">\r\n                "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbParti();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n\r\n</div>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
