<%@ Page Inherits="Microsoft.SharePoint.Publishing.TemplateRedirectionPage,Microsoft.SharePoint.Publishing,Version=15.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %> <%@ Reference VirtualPath="~TemplatePageUrl" %> <%@ Reference VirtualPath="~masterurl/custom.master" %><%@ Register Tagprefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<html xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"><head>
<!--[if gte mso 9]><SharePoint:CTFieldRefs runat=server Prefix="mso:" FieldList="FileLeafRef,Comments,PublishingStartDate,PublishingExpirationDate,PublishingContactEmail,PublishingContactName,PublishingContactPicture,PublishingPageLayout,PublishingVariationGroupID,PublishingVariationRelationshipLinkFieldID,PublishingRollupImage,Audience,PublishingIsFurlPage,PublishingPageImage,PublishingPageContent,SummaryLinks,ArticleByLine,ArticleStartDate,PublishingImageCaption,HeaderStyleDefinitions,SeoBrowserTitle,SeoMetaDescription,SeoKeywords,RobotsNoIndex"><xml>
<mso:CustomDocumentProperties>
<mso:PublishingPageContent msdt:dt="string">&lt;div class=&quot;ms-rtestate-read ms-rte-wpbox&quot; unselectable=&quot;on&quot;&gt;&lt;div class=&quot;ms-rtestate-notify  ms-rtestate-read 61687c82-17c4-4ec2-80b9-3a024bf7a925&quot; id=&quot;div_61687c82-17c4-4ec2-80b9-3a024bf7a925&quot; unselectable=&quot;on&quot;&gt;&lt;/div&gt;&lt;div id=&quot;vid_61687c82-17c4-4ec2-80b9-3a024bf7a925&quot; unselectable=&quot;on&quot; style=&quot;display&amp;#58;none;&quot;&gt;&lt;/div&gt;&lt;/div&gt;&lt;p&gt;&amp;#160;&lt;/p&gt;
&lt;table class=&quot;Content&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;DEVELOPMENT PIEPELINE&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                        &lt;a href=&quot;#&quot;&gt;AML Development Pipeline&lt;/a&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;td&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;START&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                        &lt;a href=&quot;#&quot;&gt;AML STArT&lt;/a&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;td&gt;&lt;div class=&quot;righttab&quot;&gt;&lt;h2&gt;Opportunities in AML&lt;/h2&gt;&lt;hr /&gt; 
               &lt;a href=&quot;#&quot;&gt;Ambit - Quizartinib&lt;/a&gt; 
               &lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;DEVELOPMENT PROFILES&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                        &lt;a href=&quot;#&quot;&gt;AML Development Profiles&lt;/a&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;td&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;OTHER HELPFUL DOCUMENTS&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt;
                        &lt;a href=&quot;#&quot;&gt;AML and quizartinib.pptx&lt;/a&gt; 
                        &lt;a href=&quot;#&quot;&gt;ESMO AML Guidelines 2013.pdf&lt;/a&gt; 
                        &lt;a href=&quot;#&quot;&gt;NCCN AML Guidelines V2 2013&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;</mso:PublishingPageContent>

</mso:CustomDocumentProperties>
</xml></SharePoint:CTFieldRefs><![endif]-->
<title>AML Insights: Today and Tomorrow</title></head>