<%@ Page Inherits="Microsoft.SharePoint.Publishing.TemplateRedirectionPage,Microsoft.SharePoint.Publishing,Version=15.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %> <%@ Reference VirtualPath="~TemplatePageUrl" %> <%@ Reference VirtualPath="~masterurl/custom.master" %><%@ Register Tagprefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<html xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"><head>
<!--[if gte mso 9]><SharePoint:CTFieldRefs runat=server Prefix="mso:" FieldList="FileLeafRef,Comments,PublishingStartDate,PublishingExpirationDate,PublishingContactEmail,PublishingContactName,PublishingContactPicture,PublishingPageLayout,PublishingVariationGroupID,PublishingVariationRelationshipLinkFieldID,PublishingRollupImage,Audience,PublishingIsFurlPage,PublishingPageImage,PublishingPageContent,SummaryLinks,ArticleByLine,ArticleStartDate,PublishingImageCaption,HeaderStyleDefinitions,SeoBrowserTitle,SeoMetaDescription,SeoKeywords,RobotsNoIndex"><xml>
<mso:CustomDocumentProperties>
<mso:PublishingPageContent msdt:dt="string">&lt;table class=&quot;Content&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;title&quot; colspan=&quot;2&quot;&gt;Step 1&amp;#58; Evaluate the Current Market and Clinical Insight of the Indication
            &lt;hr /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;
            &lt;img style=&quot;width:450px;height:200px;&quot; alt=&quot;red&quot; src=&quot;/sites/diligence/Style%20Library/DiligencePortal/images/red.png&quot; /&gt;&lt;/td&gt;&lt;td&gt;&lt;p&gt;The first step is often performed behind the scenes and driven by the current situation, and history, of the indication. It can be done at any time and is not directly related to the opportunity to be evaluated. A library of reference material can be generated in this process that can be used in several opportunities. This process requires a strategic deep-dive, but the data gathered are time-limited and must be updated regularly as the current situation changes.
               number of patients with the disease and the treatment flow through the healthcare system must be evaluated&amp;#58; Is this an unmet need? What are the value drivers? These factors can vary dramatically between countries and regions. The treatments that are already available, including the current standard of care, are also identified during this process. 
            &lt;/p&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;title&quot; colspan=&quot;2&quot;&gt;Step 2&amp;#58; Evaluate the Future Market and Clinical Insight of the Indication
            &lt;hr /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;
            &lt;img width=&quot;450&quot; height=&quot;200&quot; alt=&quot;green&quot; src=&quot;/sites/diligence/Style%20Library/DiligencePortal/images/green.png&quot; /&gt;&lt;/td&gt;&lt;td&gt;&lt;p&gt;
            Like the first step, the evaluation of the future market for the indication is also performed behind the scenes and driven by the indication and not the opportunity. It is often performed at the same time as the first step and is not directly related to the opportunity to be evaluated. The data gathered are hypotheses and predictions based on the current situation and history of the indication.  
            Several key pieces of information must be considered during this process&amp;#58; What are the impacts on studies in this indication? How may the patient flow change in the future? Is the standard of care likely to change in the next few years. What are the value drivers likely to be in the future? What activities are happening in the current market that may come into fruition in the coming years (e.g. what other therapeutics may be licensed and by when?)         
            &lt;/p&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;title&quot; colspan=&quot;2&quot;&gt;Step 3&amp;#58; Review the Opportunity 
            &lt;hr /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;
            &lt;img width=&quot;450&quot; height=&quot;200&quot; alt=&quot;purple&quot; src=&quot;/sites/diligence/Style%20Library/DiligencePortal/images/purple.png&quot; /&gt;&lt;/td&gt;&lt;td&gt;&lt;p&gt;
            To review the opportunity, a prior good depth of knowledge of the indication is required (Step 1 and Step 2). This is a cross-functional, multi-faceted process that spans several activities. initially the opportunity is brought to the functional head for review (FHR). If given the go ahead, the opportunity is presented to the Licensing Leadership Team (LLT) for a wider, top-line review and approval. If successful, members of the due diligence team are identified from each function (Regulatory, Medical Science, CMC, Business Development, Patent, etc) where a confidential presentation of the opportunity is given by the company and if the product is still favoured by the team, an e.room is opened. This information is evaluated and each member of the team drafts a Cross-Functional Product Assessment (CFPA). Using this information, facilitated LLT SWOT exercise is performed to identify the products&#39; Strengths, Weaknesses, Opportunities and Threats; considerations are taken from all team members and the SWOTs are ranked according to priority and seriousness. Meanwhile, Intellectual Property (IP) searches are initiated, a Business Case 1 (BC1) and a Target Product Profile (TPP) is produced. When all the available information is digested, any gaps in the data or outstanding questions are identified by each team member and an on-site visit is scheduled. Select members of the Due Diligence team visit the company to receive conformation of the information already received and to and ensure that all questions and data gaps are addressed during this time. With a complete and informed approach, a final Due Diligence Report and a second Business Case (BC2) are completed.           
            &lt;/p&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;title&quot; colspan=&quot;2&quot;&gt;Step 4&amp;#58; Complete the Development Plan 
            &lt;hr /&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;
            &lt;img width=&quot;450&quot; height=&quot;200&quot; alt=&quot;blue&quot; src=&quot;/sites/diligence/Style%20Library/DiligencePortal/images/blue.png&quot; /&gt;&lt;/td&gt;&lt;td&gt;&lt;p&gt;
            Upon completion of the review of the opportunity by the Due diligence team, a full development plan will be written. This must include all the relevant commercial and regulatory considerations in order to meet the TPP and get market approval. A full suitable Phase 3 programme must be designed if required. Integrated Project Plans (IPP) are completed and Workbooks are developed. Upon completion of the development plan, the teams findings are submitted to the Board of Directors for the decision to approve or reject bringing the opportunity in-house for further development and registration.
&lt;/p&gt;&lt;div class=&quot;ms-rtestate-read ms-rte-wpbox&quot; unselectable=&quot;on&quot;&gt;&lt;div class=&quot;ms-rtestate-notify  ms-rtestate-read 48b36da0-8e85-4544-be5e-ea371b13adff&quot; id=&quot;div_48b36da0-8e85-4544-be5e-ea371b13adff&quot; unselectable=&quot;on&quot;&gt;&lt;/div&gt;&lt;div id=&quot;vid_48b36da0-8e85-4544-be5e-ea371b13adff&quot; unselectable=&quot;on&quot; style=&quot;display&amp;#58;none;&quot;&gt;&lt;/div&gt;&lt;/div&gt;&lt;p&gt;            &amp;#160;&lt;/p&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;</mso:PublishingPageContent>
</mso:CustomDocumentProperties>
</xml></SharePoint:CTFieldRefs><![endif]-->
<title>Diligence Process</title></head>