<%@ Page Inherits="Microsoft.SharePoint.Publishing.TemplateRedirectionPage,Microsoft.SharePoint.Publishing,Version=15.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %> <%@ Reference VirtualPath="~TemplatePageUrl" %> <%@ Reference VirtualPath="~masterurl/custom.master" %><%@ Register Tagprefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<html xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"><head>
<!--[if gte mso 9]><SharePoint:CTFieldRefs runat=server Prefix="mso:" FieldList="FileLeafRef,Comments,PublishingStartDate,PublishingExpirationDate,PublishingContactEmail,PublishingContactName,PublishingContactPicture,PublishingPageLayout,PublishingVariationGroupID,PublishingVariationRelationshipLinkFieldID,PublishingRollupImage,Audience,PublishingIsFurlPage,PublishingPageImage,PublishingPageContent,SummaryLinks,ArticleByLine,ArticleStartDate,PublishingImageCaption,HeaderStyleDefinitions,SeoBrowserTitle,SeoMetaDescription,SeoKeywords,RobotsNoIndex"><xml>
<mso:CustomDocumentProperties>
<mso:PublishingPageContent msdt:dt="string">&lt;div class=&quot;title&quot; style=&quot;height&amp;#58;50px;&quot;&gt; 
   &lt;h2&gt;Background Information to-BBB - 2B3-101&lt;/h2&gt;&lt;/div&gt;&lt;div&gt;&lt;div&gt;&lt;h3&gt;General Information&lt;/h3&gt;&lt;hr /&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;HOW TO ACCESS THE DATA ROOM&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; ShareVault name&amp;#58;toBBB&lt;br&gt; You can login at 
                  &lt;a href=&quot;#&quot;&gt;tobbb.ShareVault.net&lt;/a&gt; or 
                  &lt;a href=&quot;#&quot;&gt;www.sharevault.net&lt;/a&gt;.&lt;br&gt;&lt;br&gt; To login, enter your e-mail address and your Sharevault password.If you&#39;ve forgotten your password, simply click on the Forgot Password link on the login page and follow the instructions.&lt;br&gt;&lt;br&gt; For Sharevault technical support, please email 
                  &lt;a href=&quot;#&quot;&gt;support@sharevault.net&lt;/a&gt;, or call our support hotline on +1.408.717.4955, ext. 2 (worldwide). &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;PRESENTATIONS&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt;
                  &lt;a href=&quot;#&quot;&gt;to-BBB-Mundipharma22ndJunly2013 final.pdf&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;WEB LINKS AND PUBLISHED LITERATURE&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                  &lt;a href=&quot;#&quot;&gt;to-BBB PK Pager.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;to-BBB PK Pager 2.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Drug Delivery to the Brain,AAPS 2014.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Doxil®——The first FDA-approved nano-drug&amp;#58; Lessons learned&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.1.1 PK,brain del,Eff.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;FDA Draft Guidance Liposome 2002.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;FDA Draft Guidance Generic DoxoHCI 2013.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.5.1.2.2 Phase I dose esc poster.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.5.1.2.3 Phase I dose esc abstract.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.5.1.2.4 Phase I-IIa CNS targeted.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;2.2 Poster PEGylated liposomes 2014.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;2.5 Gaillard 2012.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;2.6 Gaillard 2014.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.2.1.1 Poster AACR 2012.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;2B3-101-CR001 ESMO 2013 poster.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;Prolonged Circulation Time Doxorubicin Encapsulated.pdf&lt;/a&gt;&lt;br&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;USEFUL INFORMATION&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                  &lt;a href=&quot;#&quot;&gt;Brief overview&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.1.1 IB.pdf&lt;/a&gt;&lt;br&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;TO-BBB CORRESPONDANCE&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                  &lt;a href=&quot;#&quot;&gt;2013 08 19 to-BBB receives IND approval for 2B3-101 and proceeds to pharse lla clinical trials.pdf&lt;/a&gt;&lt;br&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;div class=&quot;ms-rtestate-read ms-rte-wpbox&quot;&gt;&lt;div class=&quot;ms-rtestate-notify  ms-rtestate-read c20138bb-8763-4a79-9c70-4ef4a9994569&quot; id=&quot;div_c20138bb-8763-4a79-9c70-4ef4a9994569&quot; unselectable=&quot;on&quot;&gt;&lt;/div&gt;&lt;div id=&quot;vid_c20138bb-8763-4a79-9c70-4ef4a9994569&quot; unselectable=&quot;on&quot; style=&quot;display&amp;#58;none;&quot;&gt;&lt;/div&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/div&gt;&lt;div class=&quot;ContentRight&quot;&gt;&lt;h3&gt;Function Specific Information&lt;/h3&gt;&lt;hr /&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;CMC&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                  &lt;a href=&quot;#&quot;&gt;3.1.3.1.1 IMPD.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.3.2.1.4 CMC Project Plan.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.3.2.2.1 Formulation and Dev.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.3.2.2.3 Photostability.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.3.2.2.4 In vitro release.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.3.2.2.5 Lipid Degradation.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.3.2.2.6 2B3 release.pdf&lt;/a&gt;&lt;br&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;NON-CLINICAL&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                  &lt;a href=&quot;#&quot;&gt;3.1.1.2 Eff at MTD.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.2.1.3 Distribution studies.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.2.1.4 Plasma conc rats.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.2.2.4 Irwin test.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.4.2.1.18 EEG effect.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.4.2.1.20 Eff of dox.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.4.2.1.21 Tiss Dist.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.4.2.1.22 Eff at MTD in mouse.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.4.2.1.26 Tiss Analysis in rats.pdf&lt;/a&gt;&lt;br&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;CLINICAL&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                  &lt;a href=&quot;#&quot;&gt;3.1.5.1.1.1A CR001 Protocol.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.5.1.1.1B CR001 Protocol.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.5.2.1.1 Study IIT Protocol.pdf&lt;/a&gt;&lt;br&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;CLINICAL SAFETY&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                  &lt;a href=&quot;#&quot;&gt;3.1.4.1.3 SUSAR Pt 094206.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.1.4 SUSAR Pt 060802.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.5.1.3.2 Safety Report 2.pdf&lt;/a&gt;&lt;br&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;top&quot;&gt;REGULATORY&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;middle&quot;&gt; 
                  &lt;a href=&quot;#&quot;&gt;3.1.4.3.1.3 MEB SA Meeting mins.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.3.1.4 MEB SA.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.3.2.2 MPA Minutes.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.4.1.2A Pre-IND Briefing Doc.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.4.1.2B Pre-IND Briefing Doc.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.4.1.3 FDA Pre-IND meeting mins.pdf&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;#&quot;&gt;3.1.4.5.2.3 EMA Briefing Doc for Glioma.pdf&lt;/a&gt;&lt;br&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class=&quot;bottom&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/div&gt;&lt;/div&gt;</mso:PublishingPageContent>
</mso:CustomDocumentProperties>
</xml></SharePoint:CTFieldRefs><![endif]-->
<title>View Background Information</title></head>