//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MR.SP.IdeaTracker.Pages.Layouts.MR.SP.IdeaTracker.Pages {
    
    
    public partial class IdeaNewPage {
    }
}
